import { expect, test, type Page } from "@playwright/test";

async function login(page: Page) { await page.goto("/"); await page.getByLabel("Email").fill("admin@example.test"); await page.getByLabel("Пароль").fill("correct horse battery staple"); await page.getByRole("button", { name: "Войти", exact: true }).click(); await expect(page).toHaveURL(/\/app$/); }

test("PostgreSQL FTS ranks title, opens RU/EN result and renders safe highlight", async ({ page }) => {
  await login(page); const notebook = await page.request.post("/api/notebooks", { data: { title: "FTS E2E" } }).then((response) => response.json()); const section = await page.request.post("/api/sections", { data: { notebookId: notebook.notebook.id, parentId: null, title: "Поиск" } }).then((response) => response.json()); const titlePage = await page.request.post("/api/pages", { data: { sectionId: section.section.id, title: "PostgreSQL уникальный" } }).then((response) => response.json()); const contentPage = await page.request.post("/api/pages", { data: { sectionId: section.section.id, title: "Другая страница" } }).then((response) => response.json()); await page.request.patch(`/api/pages/${contentPage.page.id}`, { data: { expectedRevision: 0, content: [{ type: "paragraph", content: [{ type: "text", text: "PostgreSQL резервное копирование", styles: {} }] }] } });
  await page.getByRole("button", { name: "Поиск" }).click(); await page.getByPlaceholder("Поиск по заметкам…").fill("postgr"); const results = page.getByRole("option"); await expect(results.first()).toContainText("PostgreSQL уникальный"); await expect(results.first().locator("mark")).toBeVisible(); await results.first().click(); await expect(page).toHaveURL(new RegExp(`/pages/${titlePage.page.id}$`));
});

test("custom template creates a page with BlockNote custom blocks", async ({ page }) => {
  await login(page); const notebook = await page.request.post("/api/notebooks", { data: { title: "Templates E2E" } }).then((response) => response.json()); const section = await page.request.post("/api/sections", { data: { notebookId: notebook.notebook.id, parentId: null, title: "From template" } }).then((response) => response.json()); const template = await page.request.post("/api/templates", { data: { name: "Runbook E2E", description: "Callout template", icon: "book-open", content: [{ type: "callout", props: { kind: "warning", title: "Важно" }, content: [{ type: "text", text: "Проверьте backup", styles: {} }] }, { type: "toggle", props: { open: true }, content: [{ type: "text", text: "Детали", styles: {} }], children: [{ type: "codeBlock", props: { language: "bash" }, content: [{ type: "text", text: "pg_dump", styles: {} }] }] }] } }).then((response) => response.json()); const created = await page.request.post("/api/pages", { data: { sectionId: section.section.id, templateId: template.template.id } }).then((response) => response.json()); await page.goto(`/pages/${created.page.id}`); await expect(page.locator(".notebook-callout")).toContainText("Проверьте backup"); await expect(page.locator(".notebook-toggle")).toContainText("Детали"); await page.reload(); await expect(page.locator('[data-content-type="codeBlock"]')).toContainText("pg_dump");
});

test("print dialog and standalone HTML export are available", async ({ page }) => {
  await login(page); const notebooks = await page.request.get("/api/notebooks").then((response) => response.json()); const section = notebooks.notebooks.at(-1).sections[0]; const created = await page.request.post("/api/pages", { data: { sectionId: section.id, title: "Printable E2E" } }).then((response) => response.json()); await page.goto(`/pages/${created.page.id}`); const archive = await page.request.get(`/api/data/export/page/${created.page.id}?format=html`); expect(archive.ok()).toBeTruthy(); expect(archive.headers()["content-type"]).toContain("application/zip"); await expect(page.locator(".notebook-print-title")).toContainText("Printable E2E");
});
