"use client";

import { useCallback, useEffect, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { Archive, Download, FileImage, HardDrive, Loader2, RefreshCw, Trash2, Upload, X } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { api, jsonOptions } from "@/lib/client-api";
import type { Notebook } from "./types";

type Stats = { notebooks: number; pages: number; versions: number; attachments: number; attachmentBytes: number; unusedAttachments: number; unusedBytes: number };
type Attachment = { id: string; originalName: string; mimeType: string; size: number; createdAt: string; used: boolean; page: null | { id: string; title: string; deletedAt: string | null; section: { id: string; title: string; notebook: { id: string; title: string } } } };
type Audit = { missingFiles: { id: string; name: string }[]; orphanFiles: { storageName: string; size: number }[]; unusedAttachments: { id: string; name: string; size: number }[]; reclaimableBytes: number };
type Summary = { kind: "page" | "notebook" | "all" | "backup"; title: string; notebooks: number; sections: number; pages: number; attachments: number; totalBytes: number };
const size = (bytes: number) => new Intl.NumberFormat("ru", { style: "unit", unit: bytes >= 1024 * 1024 ? "megabyte" : "kilobyte", maximumFractionDigits: 1 }).format(bytes / (bytes >= 1024 * 1024 ? 1024 * 1024 : 1024));

export function DataSettings({ open, onOpenChange, notebooks, activeSectionId, onChanged, onOpenPage, onError }: { open: boolean; onOpenChange(open: boolean): void; notebooks: Notebook[]; activeSectionId: string | null; onChanged(): Promise<void>; onOpenPage(pageId: string): void; onError(error: unknown): void }) {
  const [stats, setStats] = useState<Stats | null>(null); const [attachments, setAttachments] = useState<Attachment[]>([]); const [nextCursor, setNextCursor] = useState<string | null>(null); const [audit, setAudit] = useState<Audit | null>(null); const [file, setFile] = useState<File | null>(null); const [summary, setSummary] = useState<Summary | null>(null); const [destination, setDestination] = useState(activeSectionId ?? ""); const [restoreFile, setRestoreFile] = useState<File | null>(null); const [confirmation, setConfirmation] = useState(""); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  const load = useCallback(async (cursor?: string) => { try { const [statsResponse, attachmentResponse] = await Promise.all([api<{ stats: Stats }>("/api/data/stats"), api<{ attachments: Attachment[]; nextCursor: string | null }>(`/api/attachments?limit=25${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ""}`)]); setStats(statsResponse.stats); setAttachments((current) => cursor ? [...current, ...attachmentResponse.attachments] : attachmentResponse.attachments); setNextCursor(attachmentResponse.nextCursor); } catch (error) { onError(error); } }, [onError]);
  useEffect(() => { if (!open) return; void Promise.resolve().then(() => load()); }, [open, load]);
  async function previewImport() { if (!file) return; setBusy("preview"); setMessage(""); try { const result = await api<{ summary: Summary }>("/api/data/import/preview", { method: "POST", headers: { "content-type": file.type || "application/octet-stream" }, body: file }); setSummary(result.summary); } catch (error) { onError(error); } finally { setBusy(""); } }
  async function runImport() { if (!file || !summary) return; if (summary.kind === "page" && !destination) { onError(new Error("Выберите раздел назначения")); return; } setBusy("import"); try { await api(`/api/data/import${summary.kind === "page" ? `?sectionId=${encodeURIComponent(destination)}` : ""}`, { method: "POST", headers: { "content-type": file.type || "application/octet-stream" }, body: file }); setMessage("Импорт завершён"); setFile(null); setSummary(null); await onChanged(); await load(); } catch (error) { onError(error); } finally { setBusy(""); } }
  async function runAudit() { setBusy("audit"); try { setAudit((await api<{ audit: Audit }>("/api/attachments/audit")).audit); } catch (error) { onError(error); } finally { setBusy(""); } }
  async function cleanup() { if (!audit || !window.confirm(`Удалить ${audit.unusedAttachments.length + audit.orphanFiles.length} неиспользуемых объектов и освободить ${size(audit.reclaimableBytes)}?`)) return; setBusy("cleanup"); try { await api("/api/attachments/audit", jsonOptions("DELETE")); setMessage("Хранилище очищено"); setAudit(null); await load(); } catch (error) { onError(error); } finally { setBusy(""); } }
  async function removeAttachment(item: Attachment) { if (item.used || !window.confirm(`Удалить «${item.originalName}»?`)) return; try { await api(`/api/attachments/${item.id}`, jsonOptions("DELETE")); await load(); } catch (error) { onError(error); } }
  async function restore() { if (!restoreFile || confirmation !== "RESTORE") return; if (!window.confirm("Существующие данные Notebook будут заменены. Продолжить?")) return; setBusy("restore"); try { await api("/api/data/restore", { method: "POST", headers: { "content-type": restoreFile.type || "application/zip", "x-notebook-confirmation": confirmation }, body: restoreFile }); setMessage("Восстановление завершено"); setRestoreFile(null); setConfirmation(""); await onChanged(); } catch (error) { onError(error); } finally { setBusy(""); } }
  const sections = notebooks.flatMap((notebook) => notebook.sections.map((section) => ({ id: section.id, label: `${notebook.title} / ${section.title}` })));
  return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/35"/><Dialog.Content className="fixed inset-0 z-50 flex flex-col overflow-hidden bg-card sm:inset-x-auto sm:left-1/2 sm:top-[5vh] sm:h-[90vh] sm:w-[min(94vw,820px)] sm:-translate-x-1/2 sm:rounded-2xl sm:shadow-2xl" aria-describedby={undefined}>
    <header className="flex h-14 shrink-0 items-center gap-3 border-b border-border/60 px-4"><HardDrive size={18}/><Dialog.Title className="flex-1 font-semibold">Настройки · Данные</Dialog.Title><Dialog.Close className="flex size-11 items-center justify-center rounded-lg text-muted-foreground hover:bg-accent" aria-label="Закрыть"><X size={18}/></Dialog.Close></header>
    <div className="min-h-0 flex-1 space-y-5 overflow-y-auto p-4 sm:p-6">{message && <button className="w-full rounded-xl bg-accent px-4 py-3 text-left text-sm" onClick={() => setMessage("")}>{message}</button>}
      <section className="rounded-2xl bg-muted/40 p-4"><h2 className="font-medium">Использование хранилища</h2>{stats ? <div className="mt-3 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Stat label="Блокноты" value={stats.notebooks}/><Stat label="Страницы" value={stats.pages}/><Stat label="Версии" value={stats.versions}/><Stat label="Вложения" value={`${stats.attachments} · ${size(stats.attachmentBytes)}`}/><Stat label="Не используется" value={`${stats.unusedAttachments} · ${size(stats.unusedBytes)}`}/></div> : <Loader2 className="mt-4 animate-spin text-muted-foreground"/>}</section>
      <section className="rounded-2xl ring-1 ring-border/60"><div className="p-4"><h2 className="font-medium">Export и backup</h2><p className="mt-1 text-sm text-muted-foreground">Экспорт переносит активный контент. Backup дополнительно включает историю и корзину, но не auth/session данные.</p></div><div className="flex flex-wrap gap-2 border-t border-border/60 p-4"><a className={buttonVariants({ variant: "outline" })} href="/api/data/export/all"><Download size={15}/>Экспортировать все данные</a><a className={buttonVariants({ variant: "outline" })} href="/api/data/backup"><Archive size={15}/>Создать резервную копию</a></div></section>
      <section className="rounded-2xl ring-1 ring-border/60"><div className="p-4"><h2 className="font-medium">Импортировать</h2><p className="mt-1 text-sm text-muted-foreground">Notebook JSON страницы либо ZIP export. Архив сначала полностью проверяется.</p><input aria-label="Файл импорта" type="file" accept=".json,.zip,application/json,application/zip" className="mt-4 block w-full text-sm" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setSummary(null); }}/>{summary?.kind === "page" && <select aria-label="Раздел назначения" value={destination} onChange={(event) => setDestination(event.target.value)} className="mt-3 h-11 w-full rounded-lg bg-background px-3 text-sm ring-1 ring-border"><option value="">Выберите раздел</option>{sections.map((section) => <option key={section.id} value={section.id}>{section.label}</option>)}</select>}{summary && <div className="mt-3 rounded-xl bg-muted p-3 text-sm"><p className="font-medium">{summary.title}</p><p className="text-muted-foreground">{summary.notebooks} блокн. · {summary.sections} разд. · {summary.pages} стр. · {summary.attachments} влож. · {size(summary.totalBytes)}</p></div>}</div><div className="flex gap-2 border-t border-border/60 p-4"><Button variant="outline" disabled={!file || Boolean(busy)} onClick={() => void previewImport()}>{busy === "preview" ? <Loader2 size={15} className="animate-spin"/> : <RefreshCw size={15}/>}Проверить импорт</Button><Button disabled={!summary || Boolean(busy)} onClick={() => void runImport()}>{busy === "import" ? <Loader2 size={15} className="animate-spin"/> : <Upload size={15}/>}Импортировать</Button></div></section>
      <section className="rounded-2xl border border-destructive/30"><div className="p-4"><h2 className="font-medium text-destructive">Восстановить из резервной копии</h2><p className="mt-1 text-sm text-muted-foreground">Текущий контент будет заменён. Перед операцией Notebook автоматически создаст safety backup.</p><input aria-label="Файл резервной копии" type="file" accept=".zip,application/zip" className="mt-4 block w-full text-sm" onChange={(event) => setRestoreFile(event.target.files?.[0] ?? null)}/><label className="mt-3 block text-sm">Введите RESTORE<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-1.5 h-11 w-full rounded-lg bg-background px-3 ring-1 ring-border"/></label></div><div className="border-t border-destructive/20 p-4"><Button variant="destructive" disabled={!restoreFile || confirmation !== "RESTORE" || Boolean(busy)} onClick={() => void restore()}>{busy === "restore" && <Loader2 size={15} className="animate-spin"/>}Восстановить</Button></div></section>
      <section className="rounded-2xl ring-1 ring-border/60"><div className="flex items-center gap-3 p-4"><div className="flex-1"><h2 className="font-medium">Вложения</h2><p className="text-sm text-muted-foreground">Использование учитывает текущие страницы и историю версий.</p></div><Button variant="outline" size="sm" onClick={() => void runAudit()} disabled={Boolean(busy)}>{busy === "audit" ? <Loader2 size={14} className="animate-spin"/> : <HardDrive size={14}/>}Проверить хранилище</Button></div>{audit && <div className="border-y border-border/60 bg-muted/40 p-4 text-sm"><p>Отсутствуют: {audit.missingFiles.length} · orphan files: {audit.orphanFiles.length} · unused: {audit.unusedAttachments.length}</p><p className="text-muted-foreground">Можно освободить {size(audit.reclaimableBytes)}</p>{(audit.unusedAttachments.length > 0 || audit.orphanFiles.length > 0) && <Button className="mt-3" variant="destructive" size="sm" onClick={() => void cleanup()}><Trash2 size={14}/>Очистить неиспользуемые вложения</Button>}</div>}<div className="divide-y divide-border/50">{attachments.map((item) => <article key={item.id} className="flex items-center gap-3 p-3"><span className="flex size-11 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-muted">{item.mimeType.startsWith("image/") ? <span role="img" aria-label="Предпросмотр изображения" className="size-full bg-cover bg-center" style={{ backgroundImage: `url(/api/uploads/${item.id})` }}/> : <FileImage size={18}/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.originalName}</p><p className="truncate text-xs text-muted-foreground">{item.mimeType} · {size(item.size)} · {new Intl.DateTimeFormat("ru", { dateStyle: "medium" }).format(new Date(item.createdAt))} · {item.used ? "используется" : "не используется"}{item.page ? ` · ${item.page.section.notebook.title} / ${item.page.section.title} / ${item.page.title}` : ""}</p></div>{item.page && !item.page.deletedAt && <Button variant="ghost" size="sm" onClick={() => onOpenPage(item.page!.id)}>Открыть</Button>}<a className={buttonVariants({ variant: "ghost", size: "icon", className: "size-11" })} href={`/api/uploads/${item.id}?download=1`} aria-label={`Скачать ${item.originalName}`}><Download size={16}/></a>{!item.used && <Button variant="ghost" size="icon" className="size-11 text-destructive" aria-label={`Удалить ${item.originalName}`} onClick={() => void removeAttachment(item)}><Trash2 size={16}/></Button>}</article>)}</div>{nextCursor && <div className="border-t border-border/60 p-3 text-center"><Button variant="ghost" disabled={Boolean(busy)} onClick={() => void load(nextCursor)}>Показать ещё</Button></div>}</section>
    </div>
  </Dialog.Content></Dialog.Portal></Dialog.Root>;
}

function Stat({ label, value }: { label: string; value: string | number }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
