"use client";

import dynamic from "next/dynamic";
import { ArrowLeft, FileText, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { t } from "@/lib/i18n/messages";
import type { EditorSaveController, Notebook, PageDocument, Section } from "./types";

const RichTextEditor = dynamic(() => import("./rich-text-editor").then((module) => module.RichTextEditor), { ssr: false, loading: () => <div className="flex flex-1 items-center justify-center text-muted-foreground"><Loader2 className="animate-spin"/></div> });

export function EditorPane({ page, notebook, section, loading, editorEpoch, onBack, onSaved, onController, onNotebookClick, onSectionClick, onInternalNavigate }: { page: PageDocument | null; notebook: Notebook | null; section: Section | null; loading: boolean; editorEpoch: number; onBack(): void; onSaved(page: PageDocument): void; onController(controller: EditorSaveController | null): void; onNotebookClick(): void; onSectionClick(): void; onInternalNavigate(pageId: string): Promise<void> }) {
  return <main className="flex h-full min-h-0 min-w-0 flex-col bg-card"><div className="notebook-no-print flex h-14 shrink-0 items-center border-b border-border/50 px-3 md:hidden"><Button variant="ghost" className="h-11" onClick={onBack}><ArrowLeft size={17}/>Страницы</Button></div>{page && <nav aria-label="Хлебные крошки" className="notebook-breadcrumbs flex min-w-0 items-center gap-1.5 border-b border-border/45 px-5 py-2 text-[13px] text-muted-foreground/90 md:px-12"><button className="max-w-[28%] truncate hover:text-foreground" title={notebook?.title} onClick={onNotebookClick}>{notebook?.title}</button><span aria-hidden="true" className="text-muted-foreground/60">/</span><button className="max-w-[28%] truncate hover:text-foreground" title={section?.title} onClick={onSectionClick}>{section?.title}</button><span aria-hidden="true" className="text-muted-foreground/60">/</span>{page.icon && <span aria-hidden="true">{page.icon}</span>}<span className="min-w-0 truncate font-medium text-foreground/85" title={page.title}>{page.title}</span></nav>}{loading ? <div className="flex flex-1 items-center justify-center text-muted-foreground"><Loader2 className="animate-spin"/></div> : page ? <RichTextEditor key={`${page.id}:${editorEpoch}`} page={page} onSaved={onSaved} onController={onController} onInternalNavigate={onInternalNavigate}/> : <div className="flex flex-1 items-center justify-center p-8 text-center"><div className="max-w-xs"><span className="mx-auto flex size-11 items-center justify-center rounded-lg bg-muted text-muted-foreground"><FileText size={20}/></span><h2 className="mt-4 font-semibold">{t("empty.selectPage")}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{t("empty.selectPageDescription")}</p></div></div>}</main>;
}
